import { AllImages } from "@/assets/AllImage";

export const openPageDB = [
  {
    id: 1,
    name: "Sunset Tree",
    userName: "Jonny Khan ",
    user: AllImages.person,
    bg: AllImages.contest.o1,
    dollar: 2600,
    vote: 59,
    time: "12:30",
  },
  {
    id: 2,
    name: "Iceland Mountains",
    userName: "Johny Khan ",
    user: AllImages.person,
    bg: AllImages.contest.o2,
    dollar: 3600,
    vote: 60,
    time: "12:30",
  },
  {
    id: 3,
    name: "Forest View",
    userName: "Noah Thompson ",
    user: AllImages.person,
    bg: AllImages.contest.o3,
    dollar: 1600,
    vote: 49,
    time: "12:30",
  },
  {
    id: 4,
    name: "Fall Foliage",
    userName: "Jonny Khan ",
    user: AllImages.person,
    bg: AllImages.contest.o4,
    dollar: 2500,
    vote: 50,
    time: "12:30",
  },
  {
    id: 5,
    name: "Winter Glen",
    userName: "Noah Thompson ",
    user: AllImages.person,
    bg: AllImages.contest.o5,
    dollar: 2600,
    vote: 59,
    time: "12:30",
  },
  {
    id: 6,
    name: "Cup with tea",
    userName: "Noah Thompson ",
    user: AllImages.person,
    bg: AllImages.contest.o6,
    dollar: 2600,
    vote: 59,
    time: "12:30",
  },
  {
    id: 7,
    name: "Basketball Blaze",
    userName: "Jonny Khan ",
    user: AllImages.person,
    bg: AllImages.contest.o7,
    dollar: 4600,
    vote: 89,
    time: "12:30",
  },
  {
    id: 8,
    name: "Colorful Birds",
    userName: "Noah Thompson ",
    user: AllImages.person,
    bg: AllImages.contest.o8,
    dollar: 2400,
    vote: 38,
    time: "12:30",
  },
  {
    id: 9,
    name: "Scenic savanna",
    userName: "Johny Khan ",
    user: AllImages.person,
    bg: AllImages.contest.o9,
    dollar: 2600,
    vote: 59,
    time: "12:30",
  },
  {
    id: 10,
    name: "Sunlit Finance",
    userName: "Noah Thompson",
    user: AllImages.person,
    bg: AllImages.contest.o10,
    dollar: 2600,
    vote: 59,
    time: "12:30",
  },
  {
    id: 11,
    name: "Park City",
    userName: "Jonny Khan ",
    user: AllImages.person,
    bg: AllImages.contest.o11,
    dollar: 2600,
    vote: 59,
    time: "12:30",
  },
  {
    id: 12,
    name: "Riverboat",
    userName: "Noah Thompson",
    user: AllImages.person,
    bg: AllImages.contest.o12,
    dollar: 2600,
    vote: 59,
    time: "12:30",
  },
];
