import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Swiper from "swiper";
import "swiper/css";
import "swiper/swiper-bundle.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Your Capture",
    template: "%s | Your Capture",
  },
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/site-icon.png",
        href: "/site-icon.png",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/site-icon.png",
        href: "/site-icon.png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>{children}</div>
      </body>
    </html>
  );
}
